# map name with name in hrimatistirio
map_scrader_name_to_market = { 
    'Amazon.com': 'AMZN'
    ,  'Apple': 'AAPL'
    , 'Tesla Motors': 'TSLA'
    , 'Google': "GOOGL"
    , 'Boeing': 'BA'
    , 'Microsoft': 'MSFT'
    , 'Walt_Disney': 'DIS'
    , 'NIKE': 'NKE'
    , 'Morgan Stanley': 'MS'
    , 'Nissan_Motor': 'NSANY'
    , 'Intel': 'INTC'
    , 'Starbucks': 'SBUX'
    , 'Barclays': 'BCS'
    , 'Sears_Holdings': 'SHLDQ'
    , 'Wells_Fargo': 'WFC'
    , 'IBM': 'IBM'
    , 'CBS': 'VIAC'
    , 'Ryanair_Holdings': 'RYAAY'
    # 'Citigroup':'C',
    # 'Wal-Mart_Stores':'WMT',
    , 'Credit_Suisse_Group':'CS'
    , 'Harley-Davidson':'HOG'
    #'3M':'MMM',
    , 'NVIDIA':'NVDA'
    # 'AT&T':'T',
    , 'Marriott_International':'MAR'
    , 'CBS':'VIAC'
    , 'Berkshire_Hathaway':'BRK.A'
    , 'Intel':'INTC'
    , 'Barclays':'BCS'
    , 'IBM':'IBM'
    , 'Lloyds_Banking_Group':'LYG'
    # 'Volkswagen_Group':'VOW',
    # 'Softbank':'SFTBY',
    # 'Renault':'RNO',
    , 'Tencent_Holdings':'TCEHY'
    , 'NIKE':'NKE'
    , 'Wells_Fargo':'WFC'
    , 'Costco_Wholesale':'COST'
    , 'Pfizer':'PFE'
    , 'MTN_Group':'MTN'
    , 'Bank_of_America':'BAC'
    , 'Qualcomm':'QCOM'
    , 'Kroger':'KR'
    , 'FedEx':'FDX'
    , 'J_Sainsbury':'SBRY'
    , 'BMW_Group':'BMW'
    , "McDonald's":'MCD'
    , 'WPP':'WPP'
    , 'Nintendo':'NTDOY'
    , 'Honda_Motor':'HMC'
    , 'Oracle':'ORCL'
    , 'Toyota_Motor':'TM'
    , 'Sears_Holdings':'SHLDQ'
    #, 'Royal_Dutch_Shell':'RDS.A'
    , 'Cisco_Systems':'CSCO'
    , 'Coca-Cola':'KO'
    , 'Novartis':'NVS'
    , 'Caterpillar':'CAT'
    , 'Nissan_Motor':'NSANY'
    , 'Tesco':'TSCO'
    , 'eBay':'EBAY'
    , 'Sony':'SNE'
    , 'Spotify':'SPOT'
    , 'Deutsche_Bank':'DB'
    , 'ZTE':'ZTCOF'
    , 'Morgan_Stanley':'MS'
    , 'BlackRock':'BLK'
    , 'Campbell_Soup':'CPB'
    , 'Verizon_Communications':'VZ'
    , 'Home_Depot':'HD'
    , 'BP':'BP'
    , 'Vodafone':'VOD'
    , 'Exxon_Mobil':'XOM'
    , 'Ford_Motor':'F'
    , 'Starbucks':'SBUX'
    #, 'Samsung_Electronics':'005930'
    #, 'KPMG':''
    , 'UBS':'UBS'
    , 'General_Motors':'GM'
    , 'Bayer':'BAYRY'
    , 'Daimler':'DDAIF'
    , 'Ryanair_Holdings':'RYAAY'
    , 'Microsoft':'MSFT'
    , 'Chipotle_Mexican_Grill':'CMG'
    , 'Broadcom':'AVGO'
    , "Moody's":'MCO'
    , 'Visa':'V'
    , 'HSBC_Holdings':'HSBC'
    , 'General_Electric':'GE'
    , 'JPMorgan_Chase':'JPM'
    , 'Unilever':'UN'
    #, 'Alibaba':'BABA'
}

articles_low_limit = 50
articles_high_limit = 400
days_to_have_articles = 50
accepted_pearson_corr = 0.5
number_of_daypoints = 15
per_of_points_to_be_pos = 0.4
per_of_raise = 0.05
nan_accepted = 0.6
